# Name of the workflow
name: Release

# Run on every commit tag which begins with "chore" (e.g., "chore: released X.X.X.X")
on:
  push:
    tags:
      - "chore*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "net7.0-windows"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false